#+TITLE: PHP SdICoop - Server

Italian e-invoicing: PHP package for implementing your web services required by the [[https://www.fatturapa.gov.it/export/fatturazione/en/sdi.htm?l=en][Italian Exchange System (SdI - "Sistema di Interscambio")]].

Please refer to
- [[https://github.com/taocomp/php-sdicoop-client][PHP SdICoop - Client]] to connect to SdI web services
- [[https://github.com/taocomp/php-sdicoop-invoice][PHP SdICoop - Invoice]] for italian electronic invoice management

* Quickstart
** Dependencies
~php-soap~

** Web Service "TrasmissioneFatture"
Just include ~examples/tramissione-fatture.php~ in your endpoint. For example, if your test endpoint is

#+BEGIN_SRC 
https://test.example.com/trasmissione/index.php
#+END_SRC

put the following code in your ~index.php~:

#+BEGIN_SRC 
<?php
require_once('/path/to/php-sdicoop-server/examples/trasmissione-fatture.php');
#+END_SRC

** Web Service "RicezioneFatture"
Just include ~examples/ricezione-fatture.php~ in your endpoint. For example, if your test endpoint is

#+BEGIN_SRC 
https://test.example.com/ricezione/index.php
#+END_SRC

put the following code in your ~index.php~:

#+BEGIN_SRC 
<?php
require_once('/path/to/php-sdicoop-server/examples/ricezione-fatture.php');
#+END_SRC

* Getting started
TODO

* Server configuration, interoperability tests and more
See [[https://forum.italia.it/c/fattura-pa][Forum Italia - Fatturazione Elettronica]] for server configuration, interoperability tests, etc. In particular:
- Apache configuration :: [[https://forum.italia.it/t/accreditamento-sdicoop-configurazione-ssl-su-apache/3314][Accreditamento SDICoop: configurazione SSL su Apache - Fatturazione Elettroni...]]
- Interoperability tests :: [[https://forum.italia.it/t/test-interoperabilita-soluzioni/4370][Test Interoperabilità Soluzioni - Fatturazione Elettronica - Forum Italia]]

If you need a "ready to start" solution, or a consultancy for your PHP project, please feel free to contact us at [[mailto:e-invoicing@taocomp.com][e-invoicing@taocomp.com]].

* Credits
We want to thank all contributors of [[https://forum.italia.it/c/fattura-pa][Forum Italia - Fatturazione Elettronica]] who have shared their snippets and any available info.

* License
GPLv3.
